---
# tasks file for linux-maintenance

- name: "Maintenance | Execute custom cleanup script"
  shell: "{{ maintenance_script }}"
  when: maintenance_script is defined

- name: "Maintenance | Finding logs to clean"
  find:
    paths: /var/log
    patterns: "*.gz,*.1"
  register: find_results

- name: "Maintenance | Cleanup compressed logs"
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ find_results['files'] }}"

- name: "Maintenance | Cleanup apt cache"
  apt:
    autoclean: yes

# Notice that we are not that kamikaze and won't purge volumes
- name: "Maintenance | Clear docker containers"
  docker_prune:
    images: yes
    networks: yes
    builder_cache: yes
    containers: yes
    containers_filters:
      until: 24h
  register: docker_clean

- debug:
    msg: >
      "{{ docker_clean.containers_space_reclaimed
      + docker_clean.images_space_reclaimed }}
      bytes cleaned"

- name: "Maintenance | Refresh gpg keys"
  shell: gpg --refresh-keys

- name: "Maintenance | Update apt"
  apt:
    update_cache: yes
